/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-21 10:01:01
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-22 16:06:53
 * @FilePath      : /server/src/shared/schemas/entities/user-preferences.schema.ts
 * @Description   : User preferences schema validation for user-preferences entity
 */

import z from 'zod'
import { ObjectIdSchema, DeviceIdSchema, ThemeSchema, LanguageSchema, TimezoneSchema, NotificationPreferencesSchema, PrivacySettingsSchema, AccessibilitySettingsSchema, ContentPreferencesSchema, CreatedAtSchema, UpdatedAtSchema } from '~/shared/schemas/primitives'

/**
 * UserPreferences Schema with Business Logic Validation
 * 
 * @description Defines the structure for user preferences entities containing personalization settings.
 * Includes comprehensive user customization options for theme, notifications, privacy, accessibility, and content.
 * 
 * @field _id - MongoDB ObjectId identifier for the preferences
 * @field user_id - ObjectId reference to the preference owner (required)
 * @field session_id - ObjectId reference to the associated session (optional, null when logged out)
 * @field device_id - Device identifier for device-specific preferences (required)
 * @field theme - UI theme preference (default: "light")
 * @field language - Language preference (default: "en")
 * @field timezone - Timezone setting (default: "UTC")
 * @field notification_preferences - Notification settings object with various flags (default: comprehensive settings)
 * @field privacy_settings - Privacy control settings (default: open settings)
 * @field accessibility_settings - Accessibility enhancement settings (default: standard settings)
 * @field content_preferences - Content filtering and personalization settings (default: standard settings)
 * @field created_at - Timestamp when preferences were created (auto-generated)
 * @field updated_at - Timestamp when preferences were last updated (auto-generated)
 * 
 * @validation session_device_consistency - If session_id is provided, device_id must also be present
 * @validation timezone_format - Timezone must include forward slash (region/city format)
 */
export const UserPreferencesBaseSchema = z.object({
  _id: ObjectIdSchema,

  /** ID of the user who owns these preferences */
  user_id: ObjectIdSchema,
  
  /** ID of the session associated with these preferences */
  session_id: ObjectIdSchema.nullable().default(null),
  
  /** Unique identifier for the device */
  device_id: DeviceIdSchema,
  
  /** UI theme preference (light, dark, auto) */
  theme: ThemeSchema.default('light'),
  
  /** Language preference for the interface */
  language: LanguageSchema.default('en'),
  
  /** Timezone setting for date/time display */
  timezone: TimezoneSchema.default('UTC'),
  
  /** Notification settings for various event types */
  notification_preferences: NotificationPreferencesSchema.default({
    push: true,
    email: true,
    in_app: true,
    mentions: true,
    follows: true,
    replies: true,
    messages: true,
    group_invites: true,
    group_join_requests: true,
    event_invites: true,
    event_updates: true,
    new_features: false
  }),
  
  /** Privacy control settings for profile visibility */
  privacy_settings: PrivacySettingsSchema.default({
    direct_message: 'everyone',
    tag_permission: 'everyone',
    discoverable_by_email: true,
    discoverable_by_phone: false
  }),
  
  /** Accessibility enhancement settings */
  accessibility_settings: AccessibilitySettingsSchema.default({
    font_size: 'medium',
    reduce_motion: false,
    high_contrast: false
  }),
  
  /** Content filtering and personalization settings */
  content_preferences: ContentPreferencesSchema.default({
    sensitive_content: false,
    personalized_ads: true,
    curated_timeline: true
  }),
  
  // Timestamps
  created_at: CreatedAtSchema.default(() => new Date()),
  
  updated_at: UpdatedAtSchema.default(() => new Date())
})

export const UserPreferencesSchema = UserPreferencesBaseSchema
  .refine((data) => {
    return data.session_id === null || !!data.device_id
  }, { path: ['device_id'] })
  .refine((data) => {
    return data.timezone.includes('/')
  }, {  path: ['timezone'] })

/**
 * UserPreferences Create Schema - For creating new user preferences documents
 * 
 * @description Schema for user preferences creation operations. Excludes auto-generated fields
 * like _id, created_at, and updated_at which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits created_at - Auto-generated timestamp
 * @omits updated_at - Auto-generated timestamp
 */
export const UserPreferencesCreateSchema = UserPreferencesBaseSchema.omit({
  _id: true,
  created_at: true,
  updated_at: true
})

/**
 * UserPreferences Update Schema - For updating existing user preferences documents
 * 
 * @description Schema for user preferences update operations. All fields are optional except _id
 * (to identify the preferences) and updated_at (automatically set). Used for updating user settings.
 * 
 * @required _id - Identifies which user preferences to update
 * @required updated_at - Automatically set to current timestamp
 */
export const UserPreferencesUpdateSchema = UserPreferencesCreateSchema.partial().extend({
  _id: ObjectIdSchema,
  updated_at: UpdatedAtSchema.default(() => new Date())
})

/**
 * Type Definitions for UserPreferences Schemas
 */

/** 
 * UserPreferences Type - Inferred from UserPreferencesSchema with business logic validation
 * @description Complete user preferences object type with all validation rules applied
 */
export type UserPreferencesType = z.infer<typeof UserPreferencesSchema>

/** 
 * UserPreferences Create Type - Inferred from UserPreferencesCreateSchema
 * @description Type for creating new user preferences (excludes auto-generated fields)
 */
export type UserPreferencesCreateType = z.infer<typeof UserPreferencesCreateSchema>

/** 
 * UserPreferences Update Type - Inferred from UserPreferencesUpdateSchema  
 * @description Type for updating existing user preferences (all fields optional except _id)
 */
export type UserPreferencesUpdateType = z.infer<typeof UserPreferencesUpdateSchema>
