/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-21 10:00:42
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-21 21:27:24
 * @FilePath      : /server/src/shared/schemas/entities/user-session.schema.ts
 * @Description   : User session schema validation for user session entity
 */

import { z } from 'zod'
import { BrowserSchema,
  CreatedAtSchema,
  DeviceIdSchema, 
  DeviceNameSchema,
  IPAddressSchema,
  IsActiveSchema,
  LastActivitySchema,
  LoginHistorySchema,
  ObjectIdSchema,
  OSSchema,
  PlatformSchema,
  UpdatedAtSchema,
  UserAgentSchema 
} from '~/shared/schemas/primitives'

/**
 * UserSession Schema with Business Logic Validation
 * 
 * @description Defines the structure for user session entities tracking user login sessions and device information.
 * Includes comprehensive device fingerprinting and login history for security monitoring.
 * 
 * @field _id - MongoDB ObjectId identifier for the session
 * @field user_id - ObjectId reference to the session owner (required)
 * @field device_id - Unique device identifier (required)
 * @field device_info - Additional device information string (default: empty string)
 * @field device_name - Human-readable device name (default: "Unknown Device")
 * @field platform - Device platform (iOS, Android, Web, etc.) (default: "Unknown")
 * @field user_agent - Browser user agent string (default: empty string)
 * @field browser - Browser name and version (default: "Unknown")
 * @field os - Operating system information (default: "Unknown")
 * @field ip_address - IP address of the session (required)
 * @field is_active - Whether the session is currently active (default: true)
 * @field last_activity - Timestamp of last user activity (default: current time)
 * @field login_history - Array of login attempts and results (default: empty array)
 * @field created_at - Timestamp when session was created (auto-generated)
 * @field updated_at - Timestamp when session was last updated (auto-generated)
 * 
 * @validation login_history_format - Each login history entry must have timestamp, ip_address, and success fields
 * @validation device_id_length - Device ID must be at least 1 character long
 */
export const UserSessionBaseSchema = z.object({
  _id: ObjectIdSchema,

  /** ID of the user who owns this session */
  user_id: ObjectIdSchema,
  
  /** Unique identifier for the device */
  device_id: DeviceIdSchema,
  
  /** Additional device information and specifications */
  device_info: z.string().trim().max(500).default(''),
  
  /** Human-readable device name */
  device_name: DeviceNameSchema.default('Unknown Device'),
  
  /** Device platform (iOS, Android, Web, etc.) */
  platform: PlatformSchema.default('Unknown'),
  
  /** Browser user agent string */
  user_agent: UserAgentSchema.default(''),
  
  /** Browser name and version information */
  browser: BrowserSchema.default('Unknown'),
  
  /** Operating system information */
  os: OSSchema.default('Unknown'),
  
  /** IP address from which the session was created */
  ip_address: IPAddressSchema,
  
  /** Whether the session is currently active */
  is_active: IsActiveSchema.default(true),
  
  /** Timestamp of the last user activity */
  last_activity: LastActivitySchema.default(() => new Date()),
  
  /** Array of login attempts and their results */
  login_history: LoginHistorySchema.default([]),
  
  created_at: CreatedAtSchema.default(() => new Date()),

  updated_at: UpdatedAtSchema.default(() => new Date())
})

export const UserSessionSchema = UserSessionBaseSchema
  .refine((data) => {
    return data.login_history.every(entry => 
      entry.timestamp && 
      entry.ip_address && 
      typeof entry.success === 'boolean'
    )
  }, {
    path: ['login_history']
  }).refine((data) => {
    return data.device_id.length >= 1
  }, {
    path: ['device_id']
  })

/**
 * UserSession Create Schema - For creating new user session documents
 * 
 * @description Schema for user session creation operations. Excludes auto-generated fields
 * like _id, created_at, and updated_at which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits created_at - Auto-generated timestamp
 * @omits updated_at - Auto-generated timestamp
 */
export const UserSessionCreateSchema = UserSessionBaseSchema.omit({
  _id: true,
  created_at: true,
  updated_at: true
})

/**
 * UserSession Update Schema - For updating existing user session documents
 * 
 * @description Schema for user session update operations. All fields are optional except _id
 * (to identify the session) and updated_at (automatically set). Used for updating session activity.
 * 
 * @required _id - Identifies which user session to update
 * @required updated_at - Automatically set to current timestamp
 */
export const UserSessionUpdateSchema = UserSessionCreateSchema.partial().extend({
  _id: ObjectIdSchema,
  updated_at: UpdatedAtSchema.default(() => new Date())
})

/**
 * Type Definitions for UserSession Schemas
 */

/** 
 * UserSession Type - Inferred from UserSessionSchema with business logic validation
 * @description Complete user session object type with all validation rules applied
 */
export type UserSessionType = z.infer<typeof UserSessionSchema>

/** 
 * UserSession Create Type - Inferred from UserSessionCreateSchema
 * @description Type for creating new user sessions (excludes auto-generated fields)
 */
export type UserSessionCreateType = z.infer<typeof UserSessionCreateSchema>

/** 
 * UserSession Update Type - Inferred from UserSessionUpdateSchema  
 * @description Type for updating existing user sessions (all fields optional except _id)
 */
export type UserSessionUpdateType = z.infer<typeof UserSessionUpdateSchema>
