/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-22 22:30:00
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-22 22:30:00
 * @FilePath      : /server/src/shared/schemas/entities/bookmark.schema.ts
 * @Description   : Bookmark schema validation for bookmark entity
 */

import { z } from 'zod'
import {
  ObjectIdSchema,
  CreatedAtSchema,
  UpdatedAtSchema
} from '~/shared/schemas/primitives'

/**
 * Bookmark Schema - Entity for user post bookmarks
 * 
 * @description Defines the structure for bookmark entities representing saved posts by users.
 * Simple relationship entity that tracks which user bookmarked which post with timestamps.
 * 
 * @field _id - MongoDB ObjectId identifier for the bookmark
 * @field user_id - ObjectId reference to the user who created the bookmark
 * @field post_id - ObjectId reference to the bookmarked post
 * @field created_at - Timestamp when the bookmark was created (auto-generated)
 * @field updated_at - Timestamp when the bookmark was last updated (auto-generated)
 */
export const BookmarkSchema = z.object({
  _id: ObjectIdSchema,

  user_id: ObjectIdSchema,

  post_id: ObjectIdSchema,

  // Timestamps
  created_at: CreatedAtSchema.default(() => new Date()),

  updated_at: UpdatedAtSchema.default(() => new Date())
})

/**
 * Bookmark Create Schema - For creating new bookmark documents
 * 
 * @description Schema for bookmark creation operations. Excludes auto-generated fields
 * like _id, created_at, and updated_at which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits created_at - Auto-generated timestamp
 * @omits updated_at - Auto-generated timestamp
 */
export const BookmarkCreateSchema = BookmarkSchema.omit({
  _id: true,
  created_at: true,
  updated_at: true
})

/**
 * Bookmark Update Schema - For updating existing bookmark documents
 * 
 * @description Schema for bookmark update operations. All fields are optional except _id
 * (to identify the bookmark). Limited update scenarios for bookmark entities.
 * 
 * @required _id - Identifies which bookmark to update
 */
export const BookmarkUpdateSchema = BookmarkCreateSchema.partial().extend({
  _id: ObjectIdSchema
})

/**
 * Type Definitions for Bookmark Schemas
 */

/** 
 * Bookmark Type - Inferred from BookmarkSchema
 * @description Complete bookmark object type
 */
export type BookmarkType = z.infer<typeof BookmarkSchema>

/** 
 * Bookmark Create Type - Inferred from BookmarkCreateSchema
 * @description Type for creating new bookmarks (excludes auto-generated fields)
 */
export type BookmarkCreateType = z.infer<typeof BookmarkCreateSchema>

/** 
 * Bookmark Update Type - Inferred from BookmarkUpdateSchema  
 * @description Type for updating existing bookmarks (all fields optional except _id)
 */
export type BookmarkUpdateType = z.infer<typeof BookmarkUpdateSchema>
