/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-22 22:30:00
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-22 10:13:37
 * @FilePath      : /server/src/shared/schemas/entities/follower.schema.ts
 * @Description   : Follower schema validation for follower entity
 */

import { z } from 'zod'
import {
  ObjectIdSchema,
  CreatedAtSchema
} from '~/shared/schemas/primitives'

/**
 * Follower Schema - Entity for user following relationships
 * 
 * @description Defines the structure for follower entities representing follow relationships between users.
 * Tracks who follows whom with creation timestamp only (follows are permanent records).
 * 
 * @field _id - MongoDB ObjectId identifier for the follower relationship
 * @field user_id - ObjectId reference to the user who is following
 * @field followed_user_id - ObjectId reference to the user being followed
 * @field created_at - Timestamp when the follow relationship was created (auto-generated)
 */
export const FollowerSchema = z.object({
  _id: ObjectIdSchema,

  user_id: ObjectIdSchema,

  followed_user_id: ObjectIdSchema,

  // Timestamps
  created_at: CreatedAtSchema.default(() => new Date())
})

/**
 * Follower Create Schema - For creating new follower relationships
 * 
 * @description Schema for follower creation operations. Excludes auto-generated fields
 * like _id and created_at which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits created_at - Auto-generated timestamp
 */
export const FollowerCreateSchema = FollowerSchema.omit({
  _id: true,
  created_at: true
})

/**
 * Follower Update Schema - For updating existing follower relationships
 * 
 * @description Schema for follower update operations. All fields are optional except _id
 * (to identify the relationship). Limited update scenarios for follower entities.
 * 
 * @required _id - Identifies which follower relationship to update
 */
export const FollowerUpdateSchema = FollowerCreateSchema.partial().extend({
  _id: ObjectIdSchema
})

/**
 * Type Definitions for Follower Schemas
 */

/** 
 * Follower Type - Inferred from FollowerSchema
 * @description Complete follower relationship object type
 */
export type FollowerType = z.infer<typeof FollowerSchema>

/** 
 * Follower Create Type - Inferred from FollowerCreateSchema
 * @description Type for creating new follower relationships (excludes auto-generated fields)
 */
export type FollowerCreateType = z.infer<typeof FollowerCreateSchema>

/** 
 * Follower Update Type - Inferred from FollowerUpdateSchema  
 * @description Type for updating existing follower relationships (all fields optional except _id)
 */
export type FollowerUpdateType = z.infer<typeof FollowerUpdateSchema>
