/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-22 22:30:00
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-22 22:30:00
 * @FilePath      : /server/src/shared/schemas/entities/hashtag.schema.ts
 * @Description   : Hashtag schema validation for hashtag entity
 */

import { z } from 'zod'
import {
  ObjectIdSchema,
  HashtagSchema as HashtagNameSchema,
  HashtagPostCountSchema,
  CreatedAtSchema
} from '~/shared/schemas/primitives'

/**
 * Hashtag Schema - Entity for hashtag information
 * 
 * @description Defines the structure for hashtag entities representing trending topics and post categorization.
 * Tracks hashtag names with their usage statistics for trend analysis.
 * 
 * @field _id - MongoDB ObjectId identifier for the hashtag
 * @field name - Hashtag name (unique, without # symbol, default: required)
 * @field post_count - Number of posts using this hashtag (default: 0)
 * @field created_at - Timestamp when the hashtag was first created (auto-generated)
 */
export const HashtagSchema = z.object({
  _id: ObjectIdSchema,

  name: HashtagNameSchema,

  post_count: HashtagPostCountSchema.default(0),

  // Timestamps
  created_at: CreatedAtSchema.default(() => new Date())
})

/**
 * Hashtag Create Schema - For creating new hashtag documents
 * 
 * @description Schema for hashtag creation operations. Excludes auto-generated fields
 * like _id and created_at which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits created_at - Auto-generated timestamp
 */
export const HashtagCreateSchema = HashtagSchema.omit({
  _id: true,
  created_at: true
})

/**
 * Hashtag Update Schema - For updating existing hashtag documents
 * 
 * @description Schema for hashtag update operations. All fields are optional except _id
 * (to identify the hashtag). Typically used for updating post counts.
 * 
 * @required _id - Identifies which hashtag to update
 */
export const HashtagUpdateSchema = HashtagCreateSchema.partial().extend({
  _id: ObjectIdSchema
})

/**
 * Type Definitions for Hashtag Schemas
 */

/** 
 * Hashtag Type - Inferred from HashtagSchema
 * @description Complete hashtag object type
 */
export type HashtagType = z.infer<typeof HashtagSchema>

/** 
 * Hashtag Create Type - Inferred from HashtagCreateSchema
 * @description Type for creating new hashtags (excludes auto-generated fields)
 */
export type HashtagCreateType = z.infer<typeof HashtagCreateSchema>

/** 
 * Hashtag Update Type - Inferred from HashtagUpdateSchema  
 * @description Type for updating existing hashtags (all fields optional except _id)
 */
export type HashtagUpdateType = z.infer<typeof HashtagUpdateSchema>
