/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-22 22:30:00
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-22 22:30:00
 * @FilePath      : /server/src/shared/schemas/entities/media.schema.ts
 * @Description   : Media schema validation for media entity
 */

import { z } from 'zod'
import { 
  ObjectIdSchema,
  URLSchema,
  MediaTypeSchema,
  FileSizeSchema,
  MediaDimensionsJsonSchema,
  CreatedAtSchema
} from '~/shared/schemas/primitives'

/**
 * Media Schema - Entity for media file information
 * 
 * @description Defines the structure for media entities representing uploaded files (images, videos, etc.).
 * Stores file metadata including URL, type, size, and dimensions for content management.
 * 
 * @field _id - MongoDB ObjectId identifier for the media file
 * @field url - URL location of the uploaded media file (required)
 * @field type - Media type (image, video, audio, document, etc.) (required)
 * @field size - File size in bytes (default: 0)
 * @field media_dimensions - JSON object containing width, height, duration metadata (default: null)
 * @field created_at - Timestamp when the media was uploaded (auto-generated)
 */
export const MediaSchema = z.object({
  _id: ObjectIdSchema,

  url: URLSchema,

  type: MediaTypeSchema,

  size: FileSizeSchema.default(0),

  media_dimensions: MediaDimensionsJsonSchema.nullable().default(null),

  // Timestamps
  created_at: CreatedAtSchema.default(() => new Date())
})

/**
 * Media Create Schema - For creating new media documents
 * 
 * @description Schema for media creation operations. Excludes auto-generated fields
 * like _id and created_at which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits created_at - Auto-generated timestamp
 */
export const MediaCreateSchema = MediaSchema.omit({
  _id: true,
  created_at: true
})

/**
 * Media Update Schema - For updating existing media documents
 * 
 * @description Schema for media update operations. All fields are optional except _id
 * (to identify the media). Typically used for updating metadata or dimensions.
 * 
 * @required _id - Identifies which media to update
 */
export const MediaUpdateSchema = MediaCreateSchema.partial().extend({
  _id: ObjectIdSchema
})

/**
 * Type Definitions for Media Schemas
 */

/** 
 * Media Type - Inferred from MediaSchema
 * @description Complete media object type
 */
export type MediaType = z.infer<typeof MediaSchema>

/** 
 * Media Create Type - Inferred from MediaCreateSchema
 * @description Type for creating new media (excludes auto-generated fields)
 */
export type MediaCreateType = z.infer<typeof MediaCreateSchema>

/** 
 * Media Update Type - Inferred from MediaUpdateSchema  
 * @description Type for updating existing media (all fields optional except _id)
 */
export type MediaUpdateType = z.infer<typeof MediaUpdateSchema>
