/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-22 22:30:00
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-22 22:30:00
 * @FilePath      : /server/src/shared/schemas/entities/notification.schema.ts
 * @Description   : Notification schema validation for notification entity
 */

import { z } from 'zod'
import {
  ObjectIdSchema,
  NotificationTypeSchema,
  NotificationTitleSchema,
  NotificationMessageSchema,
  IsReadSchema,
  ReadAtSchema,
  CreatedAtSchema
} from '~/shared/schemas/primitives'

/**
 * Notification Base Schema - Core entity structure for notification data validation
 * 
 * @description Defines the complete structure of a notification entity with all required fields.
 * Notifications inform users about activities, mentions, follows, and other social interactions.
 * 
 * @field _id - MongoDB ObjectId identifier for the notification
 * @field recipient_id - ObjectId reference to the user receiving the notification (required)
 * @field sender_id - ObjectId reference to the user who triggered the notification (required)
 * @field type - Type of notification (follow, like, comment, mention, etc.) (required)
 * @field title - Notification title/heading (required)
 * @field message - Notification message content (required)
 * @field post_id - ObjectId reference to related post (default: null)
 * @field conversation_id - ObjectId reference to related conversation (default: null)
 * @field group_id - ObjectId reference to related group (default: null)
 * @field event_id - ObjectId reference to related event (default: null)
 * @field is_read - Whether the notification has been read (default: false)
 * @field read_at - Timestamp when notification was read (default: null)
 * @field created_at - Timestamp when notification was created (auto-generated)
 */
// Base schema without refinements
export const NotificationBaseSchema = z.object({
  _id: ObjectIdSchema,

  recipient_id: ObjectIdSchema,

  sender_id: ObjectIdSchema,

  type: NotificationTypeSchema,

  title: NotificationTitleSchema,

  message: NotificationMessageSchema,

  // Optional references based on notification type
  post_id: ObjectIdSchema.nullable().default(null),

  conversation_id: ObjectIdSchema.nullable().default(null),

  group_id: ObjectIdSchema.nullable().default(null),

  event_id: ObjectIdSchema.nullable().default(null),

  // Read status
  is_read: IsReadSchema.default(false),

  read_at: ReadAtSchema.nullable().default(null),

  // Timestamps
  created_at: CreatedAtSchema.default(() => new Date())
})

/**
 * Notification Schema with Business Logic Validation
 * 
 * @description Extended notification schema that includes business logic refinements and validation rules.
 * This schema ensures data integrity by validating relationships between read status and timestamp.
 * 
 * @validation read_status_consistency - If is_read is true, read_at timestamp must be present
 */
// Full schema with refinements
export const NotificationSchema = NotificationBaseSchema
  .refine((data) => {
    return !data.is_read || data.read_at
  }, { path: ['is_read'] })
  .refine((data) => {
    return data.is_read || !data.read_at
  }, { path: ['is_read'] })

/**
 * Notification Create Schema - For creating new notification documents
 * 
 * @description Schema for notification creation operations. Excludes auto-generated fields
 * like _id and created_at which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits created_at - Auto-generated timestamp
 */
export const NotificationCreateSchema = NotificationBaseSchema.omit({
  _id: true,
  created_at: true
})

/**
 * Notification Update Schema - For updating existing notification documents
 * 
 * @description Schema for notification update operations. All fields are optional except _id
 * (to identify the notification). Typically used for marking notifications as read.
 * 
 * @required _id - Identifies which notification to update
 */
export const NotificationUpdateSchema = NotificationCreateSchema.partial().extend({
  _id: ObjectIdSchema
})

/**
 * Type Definitions for Notification Schemas
 */

/** 
 * Notification Type - Inferred from NotificationSchema with business logic validation
 * @description Complete notification object type with all validation rules applied
 */
export type NotificationType = z.infer<typeof NotificationSchema>

/** 
 * Notification Create Type - Inferred from NotificationCreateSchema
 * @description Type for creating new notifications (excludes auto-generated fields)
 */
export type NotificationCreateType = z.infer<typeof NotificationCreateSchema>

/** 
 * Notification Update Type - Inferred from NotificationUpdateSchema  
 * @description Type for updating existing notifications (all fields optional except _id)
 */
export type NotificationUpdateType = z.infer<typeof NotificationUpdateSchema>
