/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-21 19:53:06
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-22 09:47:37
 * @FilePath      : /server/src/shared/schemas/entities/permission.schema.ts
 * @Description   : Permission schema validation for permission entity
 */

import { z } from 'zod'
import { ActionSchema, CreatedAtSchema, DescriptionSchema, ObjectIdSchema, PermissionNameSchema, ResourceSchema, UpdatedAtSchema } from '~/shared/schemas/primitives'

/**
 * Permission Schema - Entity for system permissions
 * 
 * @description Defines the structure for permission entities representing system access rights.
 * Permissions define what actions users can perform on specific resources in the application.
 * 
 * @field _id - MongoDB ObjectId identifier for the permission
 * @field name - Unique permission name (create_post, delete_user, etc.) (required)
 * @field description - Description of what the permission allows (default: empty string)
 * @field resource - Resource type this permission applies to (default: empty string)
 * @field action - Specific action allowed on the resource (default: empty string)
 * @field created_at - Timestamp when permission was created (auto-generated)
 * @field updated_at - Timestamp when permission was last updated (auto-generated)
 */
export const PermissionSchema = z.object({
  _id: ObjectIdSchema,

  /** Unique: create_post, delete_user,... */
  name: PermissionNameSchema,

  description: DescriptionSchema.default(''),

  resource: ResourceSchema.default(''),

  action: ActionSchema.default(''),

  // Timestamps
  created_at: CreatedAtSchema.default(() => new Date()),

  updated_at: UpdatedAtSchema.default(() => new Date())
})

/**
 * Permission Create Schema - For creating new permission documents
 * 
 * @description Schema for permission creation operations. Excludes auto-generated fields
 * like _id, created_at, and updated_at which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits created_at - Auto-generated timestamp
 * @omits updated_at - Auto-generated timestamp
 */
export const PermissionCreateSchema = PermissionSchema.omit({
  _id: true,
  created_at: true,
  updated_at: true
})

/**
 * Permission Update Schema - For updating existing permission documents
 * 
 * @description Schema for permission update operations. All fields are optional except _id
 * (to identify the permission) and updated_at (automatically set). Used for updating permission details.
 * 
 * @required _id - Identifies which permission to update
 * @required updated_at - Automatically set to current timestamp
 */
export const PermissionUpdateSchema = PermissionCreateSchema.partial()
  .extend({
    _id: ObjectIdSchema,
    updated_at: UpdatedAtSchema.default(() => new Date())
  })

/**
 * Type Definitions for Permission Schemas
 */

/** 
 * Permission Type - Inferred from PermissionSchema
 * @description Complete permission object type
 */
export type PermissionType = z.infer<typeof PermissionSchema>

/** 
 * Permission Create Type - Inferred from PermissionCreateSchema
 * @description Type for creating new permissions (excludes auto-generated fields)
 */
export type PermissionCreateType = z.infer<typeof PermissionCreateSchema>

/** 
 * Permission Update Type - Inferred from PermissionUpdateSchema  
 * @description Type for updating existing permissions (all fields optional except _id)
 */
export type PermissionUpdateType = z.infer<typeof PermissionUpdateSchema>
