/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-22 22:30:00
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-22 11:01:17
 * @FilePath      : /server/src/shared/schemas/entities/post-category.schema.ts
 * @Description   : PostCategory schema validation for post category entity
 */

import { z } from 'zod'
import {
  ObjectIdSchema,
  CategoryNameSchema,
  DescriptionSchema,
  URLSchema,
  CreatedAtSchema
} from '~/shared/schemas/primitives'

/**
 * PostCategory Schema - Entity for post categorization
 * 
 * @description Defines the structure for post category entities representing hierarchical content classification.
 * Supports nested categories through parent-child relationships for organized content taxonomy.
 * 
 * @field _id - MongoDB ObjectId identifier for the category
 * @field name - Category name (required)
 * @field description - Category description or explanation (default: empty string)
 * @field icon - URL to category icon image (required)
 * @field parent_id - ObjectId reference to parent category for hierarchy (default: null)
 * @field created_at - Timestamp when category was created (auto-generated)
 */
export const PostCategorySchema = z.object({
  _id: ObjectIdSchema,

  name: CategoryNameSchema,

  description: DescriptionSchema.default(''),

  icon: URLSchema,

  parent_id: ObjectIdSchema.nullable().default(null),

  // Timestamps
  created_at: CreatedAtSchema.default(() => new Date())
})

/**
 * PostCategory Create Schema - For creating new post category documents
 * 
 * @description Schema for post category creation operations. Excludes auto-generated fields
 * like _id and created_at which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits created_at - Auto-generated timestamp
 */
export const PostCategoryCreateSchema = PostCategorySchema.omit({
  _id: true,
  created_at: true
})

/**
 * PostCategory Update Schema - For updating existing post category documents
 * 
 * @description Schema for post category update operations. All fields are optional except _id
 * (to identify the category). Used for updating category details or hierarchy.
 * 
 * @required _id - Identifies which post category to update
 */
export const PostCategoryUpdateSchema = PostCategoryCreateSchema.partial().extend({
  _id: ObjectIdSchema
})

/**
 * Type Definitions for PostCategory Schemas
 */

/** 
 * PostCategory Type - Inferred from PostCategorySchema
 * @description Complete post category object type
 */
export type PostCategoryType = z.infer<typeof PostCategorySchema>

/** 
 * PostCategory Create Type - Inferred from PostCategoryCreateSchema
 * @description Type for creating new post categories (excludes auto-generated fields)
 */
export type PostCategoryCreateType = z.infer<typeof PostCategoryCreateSchema>

/** 
 * PostCategory Update Type - Inferred from PostCategoryUpdateSchema  
 * @description Type for updating existing post categories (all fields optional except _id)
 */
export type PostCategoryUpdateType = z.infer<typeof PostCategoryUpdateSchema>
