/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-22 22:30:00
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-22 22:30:00
 * @FilePath      : /server/src/shared/schemas/entities/post-hashtag.schema.ts
 * @Description   : PostHashtag schema validation for post-hashtag relation entity
 */

import { z } from 'zod'
import {
  ObjectIdSchema,
  CreatedAtSchema
} from '~/shared/schemas/primitives'

/**
 * PostHashtag Schema - Junction entity for post-hashtag relationships
 * 
 * @description Defines the structure for post-hashtag relationship entities representing many-to-many
 * associations between posts and hashtags. Enables hashtag-based post categorization and search.
 * 
 * @field _id - MongoDB ObjectId identifier for the relationship
 * @field post_id - ObjectId reference to the post (required)
 * @field hashtag_id - ObjectId reference to the hashtag (required)
 * @field created_at - Timestamp when the relationship was created (auto-generated)
 */
export const PostHashtagSchema = z.object({
  _id: ObjectIdSchema,

  post_id: ObjectIdSchema,

  hashtag_id: ObjectIdSchema,

  // Timestamps
  created_at: CreatedAtSchema.default(() => new Date())
})

/**
 * PostHashtag Create Schema - For creating new post-hashtag relationships
 * 
 * @description Schema for post-hashtag creation operations. Excludes auto-generated fields
 * like _id and created_at which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits created_at - Auto-generated timestamp
 */
export const PostHashtagCreateSchema = PostHashtagSchema.omit({
  _id: true,
  created_at: true
})

/**
 * PostHashtag Update Schema - For updating existing post-hashtag relationships
 * 
 * @description Schema for post-hashtag update operations. All fields are optional except _id
 * (to identify the relationship). Limited update scenarios for junction entities.
 * 
 * @required _id - Identifies which post-hashtag relationship to update
 */
export const PostHashtagUpdateSchema = PostHashtagCreateSchema.partial().extend({
  _id: ObjectIdSchema
})

/**
 * Type Definitions for PostHashtag Schemas
 */

/** 
 * PostHashtag Type - Inferred from PostHashtagSchema
 * @description Complete post-hashtag relationship object type
 */
export type PostHashtagType = z.infer<typeof PostHashtagSchema>

/** 
 * PostHashtag Create Type - Inferred from PostHashtagCreateSchema
 * @description Type for creating new post-hashtag relationships (excludes auto-generated fields)
 */
export type PostHashtagCreateType = z.infer<typeof PostHashtagCreateSchema>

/** 
 * PostHashtag Update Type - Inferred from PostHashtagUpdateSchema  
 * @description Type for updating existing post-hashtag relationships (all fields optional except _id)
 */
export type PostHashtagUpdateType = z.infer<typeof PostHashtagUpdateSchema>
