/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-22 22:30:00
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-22 22:30:00
 * @FilePath      : /server/src/shared/schemas/entities/post-post-category.schema.ts
 * @Description   : PostPostCategory schema validation for post-postCategory relation entity
 */

import { z } from 'zod'
import {
  ObjectIdSchema,
  CreatedAtSchema
} from '~/shared/schemas/primitives'

/**
 * PostPostCategory Schema - Junction entity for post-category relationships
 * 
 * @description Defines the structure for post-category relationship entities representing many-to-many
 * associations between posts and categories. Enables category-based post organization and filtering.
 * 
 * @field _id - MongoDB ObjectId identifier for the relationship
 * @field post_id - ObjectId reference to the post (required)
 * @field category_id - ObjectId reference to the category (required)
 * @field created_at - Timestamp when the relationship was created (auto-generated)
 */
export const PostPostCategorySchema = z.object({
  _id: ObjectIdSchema,

  post_id: ObjectIdSchema,

  category_id: ObjectIdSchema,

  // Timestamps
  created_at: CreatedAtSchema.default(() => new Date())
})

/**
 * PostPostCategory Create Schema - For creating new post-category relationships
 * 
 * @description Schema for post-category creation operations. Excludes auto-generated fields
 * like _id and created_at which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits created_at - Auto-generated timestamp
 */
export const PostPostCategoryCreateSchema = PostPostCategorySchema.omit({
  _id: true,
  created_at: true
})

/**
 * PostPostCategory Update Schema - For updating existing post-category relationships
 * 
 * @description Schema for post-category update operations. All fields are optional except _id
 * (to identify the relationship). Limited update scenarios for junction entities.
 * 
 * @required _id - Identifies which post-category relationship to update
 */
export const PostPostCategoryUpdateSchema = PostPostCategoryCreateSchema.partial().extend({
  _id: ObjectIdSchema
})

/**
 * Type Definitions for PostPostCategory Schemas
 */

/** 
 * PostPostCategory Type - Inferred from PostPostCategorySchema
 * @description Complete post-category relationship object type
 */
export type PostPostCategoryType = z.infer<typeof PostPostCategorySchema>

/** 
 * PostPostCategory Create Type - Inferred from PostPostCategoryCreateSchema
 * @description Type for creating new post-category relationships (excludes auto-generated fields)
 */
export type PostPostCategoryCreateType = z.infer<typeof PostPostCategoryCreateSchema>

/** 
 * PostPostCategory Update Type - Inferred from PostPostCategoryUpdateSchema  
 * @description Type for updating existing post-category relationships (all fields optional except _id)
 */
export type PostPostCategoryUpdateType = z.infer<typeof PostPostCategoryUpdateSchema>
