/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-22 22:30:00
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-22 22:30:00
 * @FilePath      : /server/src/shared/schemas/entities/reaction.schema.ts
 * @Description   : Reaction schema validation for reaction entity
 */

import { z } from 'zod'
import {
  ObjectIdSchema,
  ReactionTypeSchema,
  CreatedAtSchema
} from '~/shared/schemas/primitives'
import { ReactionType as ReactionTypeEnum } from '~/shared/enums'

/**
 * Reaction Schema - Entity for user post reactions
 * 
 * @description Defines the structure for reaction entities representing user responses to posts.
 * Tracks different types of reactions (Like, Love, Haha, Wow, Sad, Angry) with user and post associations.
 * 
 * @field _id - MongoDB ObjectId identifier for the reaction
 * @field user_id - ObjectId reference to the user who reacted (required)
 * @field post_id - ObjectId reference to the post being reacted to (required)
 * @field type - Type of reaction (Like, Love, Haha, Wow, Sad, Angry) (default: Like)
 * @field created_at - Timestamp when the reaction was created (auto-generated)
 */
export const ReactionSchema = z.object({
  _id: ObjectIdSchema,

  user_id: ObjectIdSchema,

  post_id: ObjectIdSchema,

  type: ReactionTypeSchema.default(ReactionTypeEnum.Like),

  // Timestamps
  created_at: CreatedAtSchema.default(() => new Date())
})

/**
 * Reaction Create Schema - For creating new reaction documents
 * 
 * @description Schema for reaction creation operations. Excludes auto-generated fields
 * like _id and created_at which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits created_at - Auto-generated timestamp
 */
export const ReactionCreateSchema = ReactionSchema.omit({
  _id: true,
  created_at: true
})

/**
 * Reaction Update Schema - For updating existing reaction documents
 * 
 * @description Schema for reaction update operations. All fields are optional except _id
 * (to identify the reaction). Typically used for changing reaction type.
 * 
 * @required _id - Identifies which reaction to update
 */
export const ReactionUpdateSchema = ReactionCreateSchema.partial().extend({
  _id: ObjectIdSchema
})

/**
 * Type Definitions for Reaction Schemas
 */

/** 
 * Reaction Type - Inferred from ReactionSchema
 * @description Complete reaction object type
 */
export type ReactionType = z.infer<typeof ReactionSchema>

/** 
 * Reaction Create Type - Inferred from ReactionCreateSchema
 * @description Type for creating new reactions (excludes auto-generated fields)
 */
export type ReactionCreateType = z.infer<typeof ReactionCreateSchema>

/** 
 * Reaction Update Type - Inferred from ReactionUpdateSchema  
 * @description Type for updating existing reactions (all fields optional except _id)
 */
export type ReactionUpdateType = z.infer<typeof ReactionUpdateSchema>
