/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-22 22:30:00
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-22 22:30:00
 * @FilePath      : /server/src/shared/schemas/entities/refresh-token.schema.ts
 * @Description   : RefreshToken schema validation for refresh_token entity
 */

import { z } from 'zod'
import {
  ObjectIdSchema,
  DeviceIdSchema,
  RefreshTokenSchema as TokenSchema,
  ExpiresAtSchema,
  CreatedAtSchema
} from '~/shared/schemas/primitives'

/**
 * RefreshToken Schema - Entity for JWT refresh tokens
 * 
 * @description Defines the structure for refresh token entities used in JWT authentication.
 * Stores refresh tokens with their expiration and device information for secure session management.
 * 
 * @field _id - MongoDB ObjectId identifier for the refresh token
 * @field user_id - ObjectId reference to the token owner (required)
 * @field device_id - Device identifier for token association (required)
 * @field session_id - ObjectId reference to the user session (required)
 * @field token - JWT refresh token string (required)
 * @field expires_at - Expiration timestamp for the token (required)
 * @field created_at - Timestamp when token was created (auto-generated)
 * @field updated_at - Timestamp when token was last updated (auto-generated)
 */
export const RefreshTokenSchema = z.object({
  _id: ObjectIdSchema,

  user_id: ObjectIdSchema,

  device_id: DeviceIdSchema,

  session_id: ObjectIdSchema,

  token: TokenSchema,

  expires_at: ExpiresAtSchema,

  // Timestamps
  created_at: CreatedAtSchema.default(() => new Date()),

  updated_at: CreatedAtSchema.default(() => new Date())
})

/**
 * RefreshToken Create Schema - For creating new refresh token documents
 * 
 * @description Schema for refresh token creation operations. Excludes auto-generated fields
 * like _id, created_at, and updated_at which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits created_at - Auto-generated timestamp
 * @omits updated_at - Auto-generated timestamp
 */
export const RefreshTokenCreateSchema = RefreshTokenSchema.omit({
  _id: true,
  created_at: true,
  updated_at: true  
})

/**
 * RefreshToken Update Schema - For updating existing refresh token documents
 * 
 * @description Schema for refresh token update operations. All fields are optional except _id
 * (to identify the token). Limited update scenarios for refresh tokens.
 * 
 * @required _id - Identifies which refresh token to update
 */
export const RefreshTokenUpdateSchema = RefreshTokenCreateSchema.partial().extend({
  _id: ObjectIdSchema
})

/**
 * Type Definitions for RefreshToken Schemas
 */

/** 
 * RefreshToken Type - Inferred from RefreshTokenSchema
 * @description Complete refresh token object type
 */
export type RefreshTokenType = z.infer<typeof RefreshTokenSchema>

/** 
 * RefreshToken Create Type - Inferred from RefreshTokenCreateSchema
 * @description Type for creating new refresh tokens (excludes auto-generated fields)
 */
export type RefreshTokenCreateType = z.infer<typeof RefreshTokenCreateSchema>

/** 
 * RefreshToken Update Type - Inferred from RefreshTokenUpdateSchema  
 * @description Type for updating existing refresh tokens (all fields optional except _id)
 */
export type RefreshTokenUpdateType = z.infer<typeof RefreshTokenUpdateSchema>
