/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-21 19:36:02
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-21 19:50:47
 * @FilePath      : /server/src/shared/schemas/entities/role.schema.ts
 * @Description   : Role schema validation for role entity
 */

import { z } from 'zod'
import {
  ObjectIdSchema,
  RoleNameSchema,
  CreatedAtSchema,
  UpdatedAtSchema,
  DescriptionSchema
} from '~/shared/schemas/primitives'

/**
 * Role Schema - Entity for user roles
 * 
 * @description Defines the structure for role entities representing user access levels and permissions.
 * Roles group related permissions together for easier user access management.
 * 
 * @field _id - MongoDB ObjectId identifier for the role
 * @field name - Role name (Admin, Moderator, User, etc.) (required)
 * @field description - Description of the role and its responsibilities (default: empty string)
 * @field createdAt - Timestamp when role was created (auto-generated)
 * @field updatedAt - Timestamp when role was last updated (auto-generated)
 */
export const RoleSchema = z.object({
  _id: ObjectIdSchema,

  name: RoleNameSchema,
  
  description: DescriptionSchema.default(''),

  // Timestamps
  createdAt: CreatedAtSchema.default(() => new Date()),

  updatedAt: UpdatedAtSchema.default(() => new Date())
})

/**
 * Role Create Schema - For creating new role documents
 * 
 * @description Schema for role creation operations. Excludes auto-generated fields
 * like _id, createdAt, and updatedAt which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits createdAt - Auto-generated timestamp
 * @omits updatedAt - Auto-generated timestamp
 */
export const RoleCreateSchema = RoleSchema.omit({
  _id: true,
  createdAt: true,
  updatedAt: true
})

/**
 * Role Update Schema - For updating existing role documents
 * 
 * @description Schema for role update operations. All fields are optional except _id
 * (to identify the role) and updatedAt (automatically set). Used for updating role details.
 * 
 * @required _id - Identifies which role to update
 * @required updatedAt - Automatically set to current timestamp
 */
export const RoleUpdateSchema = RoleCreateSchema.partial().extend({
  _id: ObjectIdSchema,
  updatedAt: UpdatedAtSchema.default(() => new Date())
})

/**
 * Type Definitions for Role Schemas
 */

/** 
 * Role Type - Inferred from RoleSchema
 * @description Complete role object type
 */
export type RoleType = z.infer<typeof RoleSchema>

/** 
 * Role Create Type - Inferred from RoleCreateSchema
 * @description Type for creating new roles (excludes auto-generated fields)
 */
export type RoleCreateType = z.infer<typeof RoleCreateSchema>

/** 
 * Role Update Type - Inferred from RoleUpdateSchema  
 * @description Type for updating existing roles (all fields optional except _id)
 */
export type RoleUpdateType = z.infer<typeof RoleUpdateSchema>
