/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-21 20:21:16
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-21 20:44:39
 * @FilePath      : /server/src/shared/schemas/entities/role-permision.schema.ts
 * @Description   : Role-Permission schema validation for role-permission entity
 */

import { z } from 'zod'
import { CreatedAtSchema, ObjectIdSchema } from '~/shared/schemas/primitives'

/**
 * RolePermission Schema - Junction entity for role-permission relationships
 * 
 * @description Defines the structure for role-permission relationship entities representing many-to-many
 * associations between roles and permissions. Enables flexible role-based access control (RBAC).
 * 
 * @field _id - MongoDB ObjectId identifier for the relationship
 * @field role_id - ObjectId reference to the role (required)
 * @field permission_id - ObjectId reference to the permission (required)
 * @field created_at - Timestamp when the relationship was created (auto-generated)
 */
export const RolePermissionSchema = z.object({
  _id: ObjectIdSchema,

  role_id: ObjectIdSchema,

  permission_id: ObjectIdSchema,

  created_at: CreatedAtSchema.default(() => new Date())
})

/**
 * RolePermission Create Schema - For creating new role-permission relationships
 * 
 * @description Schema for role-permission creation operations. Excludes auto-generated fields
 * like _id and created_at which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits created_at - Auto-generated timestamp
 */
export const RolePermissionCreateSchema = RolePermissionSchema.omit({
  _id: true,
  created_at: true
})

/**
 * RolePermission Update Schema - For updating existing role-permission relationships
 * 
 * @description Schema for role-permission update operations. All fields are optional except _id
 * (to identify the relationship). Limited update scenarios for junction entities.
 * 
 * @required _id - Identifies which role-permission relationship to update
 */
export const RolePermissionUpdateSchema = RolePermissionCreateSchema.partial().extend({
  _id: ObjectIdSchema,
})

/**
 * Type Definitions for RolePermission Schemas
 */

/** 
 * RolePermission Type - Inferred from RolePermissionSchema
 * @description Complete role-permission relationship object type
 */
export type RolePermissionType = z.infer<typeof RolePermissionSchema>

/** 
 * RolePermission Create Type - Inferred from RolePermissionCreateSchema
 * @description Type for creating new role-permission relationships (excludes auto-generated fields)
 */
export type RolePermissionCreateType = z.infer<typeof RolePermissionCreateSchema>

/** 
 * RolePermission Update Type - Inferred from RolePermissionUpdateSchema  
 * @description Type for updating existing role-permission relationships (all fields optional except _id)
 */
export type RolePermissionUpdateType = z.infer<typeof RolePermissionUpdateSchema>
