/*
 * @Author        : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @Date          : 2025-06-22 22:30:00
 * @LastEditors   : Phuc Nguyen nguyenhuuphuc22052004@gmail.com
 * @LastEditTime  : 2025-06-22 22:30:00
 * @FilePath      : /server/src/shared/schemas/entities/trend.schema.ts
 * @Description   : Trend schema validation for trend entity
 */

import { z } from 'zod'
import {
  ObjectIdSchema,
  TrendNameSchema,
  PostCountSchema,
  TrendScoreSchema,
  GeoPointSchema,
  CreatedAtSchema,
  UpdatedAtSchema
} from '~/shared/schemas/primitives'

/**
 * Trend Schema - Entity for trending topics and hashtags
 * 
 * @description Defines the structure for trend entities representing popular content and topics.
 * Tracks trending hashtags with their performance metrics and geographic data for analytics.
 * 
 * @field _id - MongoDB ObjectId identifier for the trend
 * @field name - Trend name or topic (required)
 * @field hashtag_id - ObjectId reference to associated hashtag (default: null)
 * @field post_count - Number of posts related to this trend (default: 0)
 * @field trend_score - Calculated trending score based on engagement (default: 0)
 * @field location - Geographic location where trend is popular (default: null)
 * @field created_at - Timestamp when trend was first detected (auto-generated)
 * @field updated_at - Timestamp when trend data was last updated (auto-generated)
 */
export const TrendSchema = z.object({
  _id: ObjectIdSchema,

  name: TrendNameSchema,

  hashtag_id: ObjectIdSchema.nullable().default(null),

  post_count: PostCountSchema.default(0),

  trend_score: TrendScoreSchema.default(0),

  location: GeoPointSchema.nullable().default(null),

  // Timestamps
  created_at: CreatedAtSchema.default(() => new Date()),

  updated_at: UpdatedAtSchema.default(() => new Date())
})

/**
 * Trend Create Schema - For creating new trend documents
 * 
 * @description Schema for trend creation operations. Excludes auto-generated fields
 * like _id, created_at, and updated_at which are handled by the database/application.
 * 
 * @omits _id - Auto-generated by MongoDB
 * @omits created_at - Auto-generated timestamp
 * @omits updated_at - Auto-generated timestamp
 */
export const TrendCreateSchema = TrendSchema.omit({
  _id: true,
  created_at: true,
  updated_at: true
})

/**
 * Trend Update Schema - For updating existing trend documents
 * 
 * @description Schema for trend update operations. All fields are optional except _id
 * (to identify the trend) and updated_at (automatically set). Used for updating trend metrics.
 * 
 * @required _id - Identifies which trend to update
 * @required updated_at - Automatically set to current timestamp
 */
export const TrendUpdateSchema = TrendCreateSchema.partial().extend({
  _id: ObjectIdSchema,
  updated_at: UpdatedAtSchema.default(() => new Date())
})

/**
 * Type Definitions for Trend Schemas
 */

/** 
 * Trend Type - Inferred from TrendSchema
 * @description Complete trend object type
 */
export type TrendType = z.infer<typeof TrendSchema>

/** 
 * Trend Create Type - Inferred from TrendCreateSchema
 * @description Type for creating new trends (excludes auto-generated fields)
 */
export type TrendCreateType = z.infer<typeof TrendCreateSchema>

/** 
 * Trend Update Type - Inferred from TrendUpdateSchema  
 * @description Type for updating existing trends (all fields optional except _id)
 */
export type TrendUpdateType = z.infer<typeof TrendUpdateSchema>
